### ISSUE TITLE
회원 가입 및 로그인 기능 구현

### ISSUE THREAD

**Issue by dd-jiyun** [WASSUP-Project/WASSUP-Server#11]
### 할 일
- [x] 패키지 구조 세팅
- [x] admin Entity 생성
- [x] jwt 일반 로그인 구현
- [x] 사용자 문자 인증
- [x] 모든 인증을 완료한 사용자 회원가입

### 내용
- 패키지 구조를 계층형을 사용할지 도메인형을 사용할지 고민하여 도메인형으로 결정하였습니다.
- RestAPI 네이밍 규칙과 Restful하게 api를 구성하는 것에 대해서 학습하였습니다.
- 사용자의 휴대폰번호로 인증번호를 발송해 인증확인을 하고 회원가입을 합니다.
- 로그인 구현을 완료합니다.(수정예정)

---
### 네이밍 규칙

- 단수보다 복수를 사용하는 것을 선호합니다. ex) /user → /users
- 동사를 사용하는 것보다 명사를 사용하는 것이 좋습니다. 또한, CRUD를 api에 넣지 않는 것이 좋습니다. ex) getUsers → GET/users
- url 끝에 / 를 넣지 않아야합니다.
- 언더바를 사용하는 것이 아닌 하이픈을 사용하여 가독성을 높입니다. ex) /developmanager → /develop-manager
- 소문자를 사용합니다.
- 필터링 시 새로운 api를 만드는 것보다 쿼리 파라미터를 사용합니다.

### RestAPI

1. 일관된 인터페이스 (Uniform interface)
    데이터를 식별 가능하게 해야하는 원칙을 말합니다.
    간결하고 일관적이어야하며, URL만 보고 어떤 데이터를 어떤 상태로 넘겨줄 것인지 구별이 가능해야합니다.
    💡 위에 작성한 네이밍 규칙이 이에 해당합니다.
    
2. 클라이언트 서버
    클라이언트와 서버는 완전히 분리되어야합니다.

3. Stateless HTTP (무상태성)
    클라이언트의 모든 요청에 해당 요청을 이해할 수 있는 모든 정보가 들어있어야 합니다.
    
4. Cacheable
    요청을 통해 전송된 데이터들은 저장되어야하며, 저장된 정보를 주고 받을 때 속도를 향상시켜줍니다.
    
5. 다중 객체 (Layered System) 
    서버와 DB, 인증 서버 구분을 두어 확장성 보장합니다.
    
6. Code on Demand
    서버가 클라이언트 측에 실행 시킬 수 있는 로직을 넘겨주고, 클라이언트가 사전에 구현해야할 기능의 수를 줄여 간소화 할 수 있습니다.

**Comment by YehyeokBang** [comment]
`accessToken` 방식으로 하신다면 `refreshToken`도 사용할 계획인가요?

**Comment by dd-jiyun** [comment]
일단은 그렇게 생각하고 있습니다!

**Comment by dd-jiyun** [comment]
### 패키지 구조

```
net
 ㄴ skhu
    ㄴwaasup
        ㄴ app
        |   ㄴ admin
        |   | ㄴ domain
        |   | ㄴ dto
        |   | ㄴ api
        |   | ㄴ service
        |   ㄴ member
        |   | ㄴ domain
        |   | ㄴ dto
        |   | ㄴ api
        |   | ㄴ service
        | ...
        ㄴ global
        |   ㄴ auth
        |   | ㄴ jwt
        |   ㄴ config
        | ...

```

**Comment by YehyeokBang** [comment]
좋아요~~

**Comment by dd-jiyun** [comment]
@YehyeokBang 위에 RestAPI에 대해서 공부한 내용을 적어봤습니다! 더 알아야 할 내용이 있을까요?! 🙇🏻‍♀️

**Comment by YehyeokBang** [comment]
확인했습니다. 감사합니다!
