### ISSUE TITLE
1차 ERD 구상

### ISSUE THREAD

**Issue by dd-jiyun** [WASSUP-Project/WASSUP-Server#2]
### 할 일
- [x] 해보고 싶었던 기술 및 레퍼런스 정리 
- [x] Figma 보고 ERD 구상

### 내용
- 사용할 기능을 정리하고 관련된 레퍼런스를 찾아본 후 정리해서 답글에 올리겠습니다.
- Figma와 프론트에서 완성한 뷰를 보며 1차 ERD를 작성 후 피드백을 받겠습니다.

### 1차 구상
<img width="1864" alt="Screenshot 2024-03-24 at 1 46 31 AM" src="https://github.com/WASSUP-Project/WASSUP-Server/assets/84395062/dbfbb0e3-ce0e-4372-823c-96a5c00ca596">

**Comment by YehyeokBang** [comment]
댓글 달았습니다!!!

**Comment by dd-jiyun** [comment]
네 확인했습니다!

**Comment by dd-jiyun** [comment]
피드백 반영해서 수정한 2차 ERD 입니다 :)

<img width="2063" alt="Screenshot 2024-03-24 at 5 39 36 PM" src="https://github.com/WASSUP-Project/WASSUP-Server/assets/84395062/e89eef97-8ecd-426d-a656-81027df576df">
