### ISSUE TITLE
그룹 관련 기능 수정 및 내 그룹 조회 기능

### ISSUE THREAD

**Issue by dd-jiyun** [WASSUP-Project/WASSUP-Server#23]
### 할 일
- [x] 그룹 수정할 때 입력받은 필드만 수정
- [x] 가입 대기 인원 및  총 가입된 인원 수 

### 내용
- 관리자가 그룹을 수정할 때 입력한 필드만 업데이트 시키고 나머지 필드는 값이 그대로 유지 됩니다.
- 관리자가 생성한 그룹들을 조회할 때 가입된 인원과 가입 대기 중인 인원을 볼 수 있습니다.

### 논의할 내용
- 사용자가 설정한 그룹 이미지를 어떻게 처리할 지 정해봐야 할 것 같습니다.

**Comment by YehyeokBang** [comment]
그룹 이미지는 `Firebase Storage`를 사용하고 웹에서 업로드 후 해당 이미지의 URL을 서버로 넘겨주는 방식으로 사용할 예정입니다!
