### ISSUE TITLE
그룹 관련 멤버 조회 기능

### ISSUE THREAD

**Issue by dd-jiyun** [WASSUP-Project/WASSUP-Server#30]
### 할 일
- [x] 그룹에 가입된 멤버의 리스트 조회
- [x] 그룹에 요청을 보낸 대기중인 멤버 리스트 조회
- [x] 위의 멤버 리스트 중 멤버 ID별 조회

### 내용
- 그룹에 가입된 멤버의 리스트를 조회합니다.
- 그룹에 가입 요청을 보낸 멤버의 리스트를 조회합니다.
- 위의 중 선택된 멤버를 조회합니다.

### 논의할 내용
- 가입을 요청한 멤버와 가입된 멤버의 리스트에서 자세히 조회하고 싶은 멤버를 클릭 시 입력한 데이터들이 조회되는데 현재 그룹에 가입되어있는 상태인지, 가입 대기 중인 상태인지도 같이 담아서 넘겨줘도 괜찮을 지 궁금합니다. (설명이 이해가 안되실 수도 있는데 질문해주세요!)

**Comment by dd-jiyun** [comment]
@YehyeokBang 논의할 내용 확인 부탁드립니다!

**Comment by YehyeokBang** [comment]
이미 가입된 멤버와 가입 대기 중인 멤버를 분리하면 좋을 것 같아요 화면 디자인을 변경하더라도 그게 나을 것 같아요.
그래서 가입 여부는 필요하지 않을 것 같아요! 다른 곳에서 대기 중인 요청들을 수락하거나 거절하고, 가입된 멤버는 기존 인원 관리에서 볼 수 있도록 하면 될 것 같아요!

**Comment by YehyeokBang** [comment]
나머지 세부 사항들은 대면 회의 시간을 활용해서 결정하면 좋을 것 같아요!

**Comment by dd-jiyun** [comment]
넵 감사합니다!
