### ISSUE TITLE
출결 기능 구현

### ISSUE THREAD

**Issue by dd-jiyun** [WASSUP-Project/WASSUP-Server#36]
### 할 일
- [x] 회의 내용을 기반으로 구현할 기능 명세서 정리
- [x] 출석 링크를 통해 멤버의 전화번호 끝 4자리 입력받고, 데이터베이스에서 조회
- [x] 해당하는 멤버의 리스트 반환 -> 중복되는 경우 선택 받을 수 있음.

#### 출결 기능 흐름
1. 관리자가 출석을 하기 위해 고유 링크를 발급 받습니다.
    - 고유 링크에는 파라미터로 중복되지 않는 고유 값이 포함되어 있습니다.
2. 발급 받음과 동시에 서버에 고유 값과 고유 링크를 발급 받은 그룹의 id 값이 캐시에 저장됩니다.
3. 고유 링크로 접속하면 출석할 수 있는 화면이 나타납니다.
4. 해당 화면에서 출석할 인원의 전화번호 끝 4자리를 입력 받습니다.
5. 고유 링크의 파라미터인 고유 값과 전화번호 끝 4자리를 서버에 전송합니다.
6. 서버에선 고유 값으로 캐시에 저장된 그룹 id를 사용하고, 전화번호 끝 4자리를 통해 출석할 인원을 찾습니다.
7. 찾은 멤버를 반환하여 출석을 합니다.
8. 만약 중복되는 경우에는 멤버 스스로 자신의 것을 찾아 선택합니다.

**Comment by YehyeokBang** [comment]
확인했습니다!

**Comment by dd-jiyun** [comment]
### 변경 사항
- **이전 방식** : 유일한 뒷번호인 경우, 자동으로 출석 처리되었습니다. 그러나 중복된 뒷번호가 존재할 경우에는 멤버를 선택하여 출석을 완료해야 했습니다.
- **변경된 방식** : 뒷번호가 일치하는 경우에도 출석 리스트가 표시되어 멤버를 선택해야 합니다. 이를 통해 입력 실수를 줄이고, 올바른 출석을 보장합니다. 멤버를 선택함으로써 입력한 정보를 다시 확인할 수 있어, 실수를 방지할 수 있습니다.

**Comment by dd-jiyun** [comment]
### 변경 사항
- **이전 방식** : 유일한 뒷번호인 경우, 자동으로 출석 처리되었습니다. 그러나 중복된 뒷번호가 존재할 경우에는 멤버를 선택하여 출석을 완료해야 했습니다.
- **변경된 방식** : 이제는 뒷번호가 일치하는 경우에도 출석 리스트가 표시되어 멤버를 선택해야 합니다. 이를 통해 입력 실수를 줄이고, 올바른 출석을 보장합니다. 멤버를 선택함으로써 입력한 정보를 다시 확인할 수 있어, 실수를 방지할 수 있습니다.

**Comment by dd-jiyun** [comment]
위와 같이 변경하였습니다 확인 부탁드립니다🙇🏻‍♀️ @YehyeokBang

**Comment by YehyeokBang** [comment]
> ### 변경 사항
> * **이전 방식** : 유일한 뒷번호인 경우, 자동으로 출석 처리되었습니다. 그러나 중복된 뒷번호가 존재할 경우에는 멤버를 선택하여 출석을 완료해야 했습니다.
> * **변경된 방식** : 이제는 뒷번호가 일치하는 경우에도 출석 리스트가 표시되어 멤버를 선택해야 합니다. 이를 통해 입력 실수를 줄이고, 올바른 출석을 보장합니다. 멤버를 선택함으로써 입력한 정보를 다시 확인할 수 있어, 실수를 방지할 수 있습니다.

네 출결과 중복 체크가 분리되어 있어서 더 좋은 기능인 것 같습니다!
