### ISSUE TITLE
배포 파이프라인 기획

### ISSUE THREAD

**Issue by dd-jiyun** [WASSUP-Project/WASSUP-Server#5]
### 할 일
- [x] 어떤 클라우드 서비스를 이용해서 배포할 지 정하기

### 내용
- 배포 파이프라인을 기획합니다.

**Comment by YehyeokBang** [comment]
### 제안
- Google Cloud Platform의 Cloud Run을 사용하여 배포하면 좋을 것 같습니다.
- GCP에서는 지속적 통합 기능을 제공합니다. `Cloud Build`로 트리거를 만들어 main 브랜치의 변경을 감지하여 자동으로 빌드하여 도커 이미지로 만들고, `Artifact Registry`에 저장합니다. 그 이후 `Cloud Run`으로 쉽게 배포할 수 있습니다.
- 데이터베이스는 따로 VM 인스턴스(aws 기준 ec2)를 사용해도 될 것 같고, 아니면 무료 크레딧을 사용하여 `Cloud SQL`을 사용해도 좋을 것 같습니다.

**Comment by dd-jiyun** [comment]
좋은 코멘트 감사합니당😆
