### ISSUE TITLE
등/하원 멤버 관리 기능 구상

### ISSUE THREAD

**Issue by dd-jiyun** [WASSUP-Project/WASSUP-Server#74]
### 내용
- 관리자가 멤버의 등/하원을 직접 수정하는 기능에 대해서 구체적으로 논의해봤으면 좋겠습니다 @YehyeokBang

**Comment by YehyeokBang** [comment]
인원 관리 페이지처럼 멤버 목록에 출결 상태를 보여주어서 관리자가 직접 수정할 수 있게 해주면 좋을 것 같아요!

**Comment by dd-jiyun** [comment]
네 저도 레퍼런스를 좀 찾아봤습니다!

![2](https://github.com/WASSUP-Project/WASSUP-Server/assets/84395062/054d116f-2c61-4989-a14c-738580961812)

<img width="1263" alt="3" src="https://github.com/WASSUP-Project/WASSUP-Server/assets/84395062/1349fd04-ce42-446a-8437-b18ac760e44f">

<img width="226" alt="아이앰" src="https://github.com/WASSUP-Project/WASSUP-Server/assets/84395062/37e42b40-2ee3-47e1-970e-d4d4f57864a7">

**Comment by YehyeokBang** [comment]
확인했습니다! 임시로 구현 후 한번 더 이야기해보면 좋을 것 같아요!
