### ISSUE TITLE
Application Level에서의 TZ 문제

### ISSUE THREAD

**Issue by YehyeokBang** [WASSUP-Project/WASSUP-Server#76]
### 설명
- 가끔 출석을 했는데도 출석률에 반영되지 않거나, 출석 이후 하원처리가 안되는 경우가 발생했었습니다. 확인해보니 저장되는 데이터 자체에는 문제가 없었지만, 데이터베이스가 저장되는 시간이 KST 기준으로 9시간이 빠져있는 상태로 저장되었습니다. 그래서 특정 시간대에서 간간히 발생했던 것 같습니다.
- MySQL 컨테이너를 띄워둔 VM 인스턴스, MySQL 컨테이너 자체, Spring Boot 실행 공간 등의 타임존을 확인해봐야할 것 같습니다!

### 할 일
- [x] VM 인스턴스 TZ 확인
- [x] MySQL TZ 확인
- [x] Spring Boot 환경 TZ 확인 (JVM)

### 결과
- Cloud Build 트리거가 GitHub의 특정 브랜치 변경을 감지하면, 준비된 Dockerfile을 사용해 이미지를 자동으로 빌드합니다. 빌드된 이미지는 Artifact Registry에 저장되고, GCP의 지속적 통합 및 배포 기능을 통해 완전 관리형 서버리스 서비스인 Cloud Run 환경에 배포됩니다.
- Cloud Run 서비스의 리전이 `us-central`으로 설정되어 있었고, 빌드된 이미지로 생성된 컨테이너도 이 리전을 따라 UTC 시간을 따르게 되었습니다. 이를 해결하기 위해, Dockerfile에 TZ(TimeZone) 환경 변수를 설정하여 컨테이너의 시간대를 Asia/Seoul로 맞추었습니다.

#### 확인
1. VM 인스턴스에 띄워져있는 MySQL 컨테이너의 TZ을 확인하니 KST로 잘 설정되어있습니다.
2. VM 인스턴스의 TZ을 확인하니 동일하게 KST로 잘 설정되어있습니다.
3. Spring Boot의 실행 공간을 확인합니다.
4. 현재 Cloud Run의 리전이 `us-central` 으로 설정되어있어 UTC 타임존으로 저장이 되었습니다.
5.  DockerFile의 Run 환경에 TZ을 설정해주었습니다.
  ```Dockerfile
  # Timezone 설정
  ENV TZ=Asia/Seoul
  RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
  ```

6. 다시 배포를 진행하니 데이터베이스에 KST로 잘 저장되었습니다.

**Comment by YehyeokBang** [comment]
<img width="1290" alt="image" src="https://github.com/WASSUP-Project/WASSUP-Server/assets/107793780/1feb7fc0-2134-479f-992b-7997c6985eb1">


<img width="1291" alt="image" src="https://github.com/WASSUP-Project/WASSUP-Server/assets/107793780/f091c3b2-c505-47d8-8176-d8ce770551f2">


<img width="288" alt="image" src="https://github.com/WASSUP-Project/WASSUP-Server/assets/107793780/1d8cd73f-c513-4a7e-9a86-7928c10ea515">

**Comment by YehyeokBang** [comment]
<img width="1290" alt="image" src="https://github.com/WASSUP-Project/WASSUP-Server/assets/107793780/1feb7fc0-2134-479f-992b-7997c6985eb1">


<img width="1291" alt="image" src="https://github.com/WASSUP-Project/WASSUP-Server/assets/107793780/f091c3b2-c505-47d8-8176-d8ce770551f2">

**Comment by dd-jiyun** [comment]
<img width="408" alt="image" src="https://github.com/WASSUP-Project/WASSUP-Server/assets/84395062/daf68015-13c8-46f1-98b8-87a592b85702">

데이터베이스에서 문제가 없다면 아마 Cloud Run의 리전이 `us-central` 이라서 그럴 수도 있을 것 같아요!
Dockerfile에서 TZ 설정을 추가해서 확인해보겠습니다!

**Comment by dd-jiyun** [comment]
<img width="383" alt="image" src="https://github.com/WASSUP-Project/WASSUP-Server/assets/84395062/beb99f5f-fa32-41e2-9d8b-352b88a829f0">

Dockerfile에서 TZ 설정을 통해 문제를 해결했습니다 이슈 닫겠습니다~!

**Comment by YehyeokBang** [comment]
확인했습니다! 이슈 닫아도 될 것 같아요!
