### ISSUE TITLE
데이터베이스 구축

### ISSUE THREAD

**Issue by dd-jiyun** [WASSUP-Project/WASSUP-Server#9]
### 할 일
- [x] VM 인스턴스에 docker 설치
- [x] MySQL 연동

### 내용
- VM 인스턴스에 Docker를 설치하여 MySQL 데이터베이스를 설정하였습니다.
- docker-compose를 이용하여 MySQL 환경을 설정해주었습니다.

**Comment by YehyeokBang** [comment]
쉬운 방법과 저렴한 비용으로 개발 단계에서 좋은 방법 같아요. 수고하셨어요~
