### ISSUE TITLE
멤버 관련 기능 수정

### ISSUE THREAD

**Issue by dd-jiyun** [WASSUP-Project/WASSUP-Server#92]
### 설명
- 수락 대기 중인 멤버와 수락된 멤버가 `api/attendances/members/{groupId}` 에서 그룹에 해당하는 모든 멤버가 반환되는 문제가 발생하였습니다.

<img width="400" alt="수락멤버" src="https://github.com/WASSUP-Project/WASSUP-Server/assets/84395062/1e8f7fa5-bee6-4f38-9659-948072222390">

<img width="400" alt="대기멤버" src="https://github.com/WASSUP-Project/WASSUP-Server/assets/84395062/e4e63aa0-aabe-46a4-a488-3384b00bb70e">

<img width="400" alt="출결멤버" src="https://github.com/WASSUP-Project/WASSUP-Server/assets/84395062/1155ac1b-0f13-49fc-b5ed-16d040431f02">

위와 같이 그룹에 해당하는 모든 멤버들의 출결 상태를 수정할 수 있게 됩니다.

### 할 일
- [x] 수락된 멤버들만 반환되게 수정

### 결과
- 결과
<img width="400" alt="image" src="https://github.com/WASSUP-Project/WASSUP-Server/assets/84395062/ecdd6a75-2d85-41a2-971e-6d93db05255d">

**Comment by YehyeokBang** [comment]
PR까지 확인했습니다!
